import torch

device = torch.device('cuda')
BATCH_SIZE = 300
LEARNING_RATE=0.0001
N_EPOCHS = 50
CLIP = 1
TRAIN_PATH = '../data/train.csv'
VALID_PATH = '../data/valid.csv'
TEST_PATH = '../data/test.csv'
X_FORMAT='csv'
GLOVE_PATH = '../glove.840B.300d.txt'
TRAIN_SPLIT=0.8
TEST_SPLIT=0.1
VALID_SPLIT=0.1
ENCODER_EMBEDDING_DIMENSION=300
DECODER_EMBEDDING_DIMENSION=300
LSTM_HIDDEN_DIMENSION = 512
LSTM_LAYERS=2
ENCODER_DROPOUT=0.5
DECODER_DROPOUT=0.5
LEARNING_RATE=0.001
MODEL_SAVE_FILE=TEST_MODEL='model_seq2seq_1.bin'
RESULTS_SAVE_FILE='results_1.txt'
TEST_RESULTS_FILE='test_1.txt'


